server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post_covid_medical_webapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 2MB



mybatis:
  configuration:
    map-underscore-to-camel-case: true


UserQualPath: "D://UserQual//"
DoctorQualPath: "D://DoctorQual//"
HospitalQualPath: "D://HospitalQual//"
commodityImgTempPath: "D://TempImg//"
